/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mibg3.Alien;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Karam Al-Akhras
 */
public class AlienMeny extends javax.swing.JFrame {
    private static String ocTel;
    private static String ocNamn;
    private InfDB mibdb;

    /**
     * Creates new form AlienMeny
     */
    public AlienMeny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        alienRutaNamn = new javax.swing.JLabel();
        välkommenAlien = new javax.swing.JLabel();
        ÄndraLösen = new javax.swing.JButton();
        InfoOmOC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        alienRutaNamn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        alienRutaNamn.setText("<ALIEN>");

        välkommenAlien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        välkommenAlien.setText("Välkommen");

        ÄndraLösen.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ÄndraLösen.setText("Ändra lösenord");
        ÄndraLösen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÄndraLösenActionPerformed(evt);
            }
        });

        InfoOmOC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        InfoOmOC.setText("Min områdeschef");
        InfoOmOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoOmOCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(alienRutaNamn)
                .addGap(132, 132, 132))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ÄndraLösen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoOmOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(213, 213, 213)
                    .addComponent(välkommenAlien)
                    .addContainerGap(228, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(alienRutaNamn)
                .addGap(36, 36, 36)
                .addComponent(ÄndraLösen)
                .addGap(26, 26, 26)
                .addComponent(InfoOmOC)
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(välkommenAlien)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ÄndraLösenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÄndraLösenActionPerformed
        // TODO add your handling code here:
        NyttLösenAlien meny = new NyttLösenAlien();
        meny.setVisible(true);
    }//GEN-LAST:event_ÄndraLösenActionPerformed

    private void InfoOmOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoOmOCActionPerformed
        // TODO add your handling code here:
        try{
            mibdb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
            String plats;
            plats = mibdb.fetchSingle("SELECT Plats FROM Alien WHERE Alien_ID = "+ "'" + (mibg3.Alien.AlienInlogg.getInloggadAlien()) + "'");
            String områdeschefID;
            områdeschefID = mibdb.fetchSingle("SELECT Agent_ID FROM Omradeschef WHERE Omrade = "+ "'" + plats + "'");
            
            ocNamn = mibdb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID = "+ "'" + områdeschefID + "'");
            ocTel = mibdb.fetchSingle("SELECT Telefon FROM Agent WHERE Agent_ID = "+ "'" + områdeschefID + "'");
            
            OmrådeschefINFO meny = new OmrådeschefINFO();
            meny.setVisible(true);
            
        }
        catch(InfException e){
            
        }
    }//GEN-LAST:event_InfoOmOCActionPerformed

    public static String getOCTel(){
    return ocTel;
}
    
    public static String getOCNamn(){
        return ocNamn;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlienMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlienMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlienMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlienMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlienMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoOmOC;
    private javax.swing.JLabel alienRutaNamn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel välkommenAlien;
    private javax.swing.JButton ÄndraLösen;
    // End of variables declaration//GEN-END:variables
}
