/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mibg3.Agent;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author d-aly
 */
public class HanteraUtrustning extends javax.swing.JFrame {
    private InfDB mibdb;

    /**
     * Creates new form HanteraUtrustning
     */
    public HanteraUtrustning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kommunikationKnapp = new javax.swing.JButton();
        vapenKommunikation = new javax.swing.JButton();
        teknikKnapp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hantera Utrustning");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Välj utrustningstyp att registrera");

        kommunikationKnapp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        kommunikationKnapp.setText("Kommunikation");
        kommunikationKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kommunikationKnappActionPerformed(evt);
            }
        });

        vapenKommunikation.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vapenKommunikation.setText("Vapen");
        vapenKommunikation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vapenKommunikationActionPerformed(evt);
            }
        });

        teknikKnapp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        teknikKnapp.setText("Teknik");
        teknikKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teknikKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kommunikationKnapp)
                .addGap(18, 18, 18)
                .addComponent(vapenKommunikation, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(teknikKnapp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kommunikationKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vapenKommunikation, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teknikKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kommunikationKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kommunikationKnappActionPerformed
        // TODO add your handling code here:
        KommunikationReg meny = new KommunikationReg();
        meny.setVisible(true);
    }//GEN-LAST:event_kommunikationKnappActionPerformed

    private void vapenKommunikationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vapenKommunikationActionPerformed
        // TODO add your handling code here:
        vapenReg meny = new vapenReg();
        meny.setVisible(true);
    }//GEN-LAST:event_vapenKommunikationActionPerformed

    private void teknikKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teknikKnappActionPerformed
        // TODO add your handling code here:
        teknikReg meny = new teknikReg();
        meny.setVisible(true);
    }//GEN-LAST:event_teknikKnappActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kommunikationKnapp;
    private javax.swing.JButton teknikKnapp;
    private javax.swing.JButton vapenKommunikation;
    // End of variables declaration//GEN-END:variables
}
