/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mibg3.Agent;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author d-aly
 */
public class SökOC extends javax.swing.JFrame {
    private InfDB mibdb;
    private ArrayList<String> områdeslista;
    private String agentNamn;
    private String områdeNamn;

    /**
     * Creates new form SökOC
     */
    public SökOC() {
        try{
            mibdb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        }
        catch(InfException e){
            JOptionPane.showMessageDialog(null, "Det gick inte att ansluta till databasen.");
        }
        initComponents();
    }
    
    private void errorMessage(){
        JOptionPane.showMessageDialog(null, "Något gick fel, vänligen försök igen.");
    }
    
    private void namnlista(){
        try{
        områdeslista = mibdb.fetchColumn("SELECT Benamning FROM Omrade");
        for(String område : områdeslista){
            områdeValCB.addItem(område);
        }
        }
        catch(InfException e){
            errorMessage();
        }
        }
    
    private String message(){
        namnlista();
        return "Vänligen välj ett område.";
    }
   
    private String getOmrådeNamn(){
        områdeNamn = områdeValCB.getSelectedItem().toString();
        return områdeNamn;
    }
   
    private String getAgentNamn(){
        String områdeID = "";
        String agentID = "";
        try{
        getOmrådeNamn();
        områdeID = mibdb.fetchSingle("SELECT Omrades_ID FROM Omrade WHERE Benamning =" + "'" + områdeNamn + "'");
        agentID = mibdb.fetchSingle("SELECT Agent_ID FROM Omradeschef WHERE Omrade =" + "'" + områdeID + "'");
        agentNamn = mibdb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID =" + "'"  + agentID + "'");
    }
        catch(InfException e){
            errorMessage();
        }
        return agentNamn;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        områdeValCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        meddelande = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        områdeValCB.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        områdeValCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                områdeValCBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Områdeschef:");

        meddelande.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        meddelande.setText(message());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText(getAgentNamn());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(områdeValCB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(meddelande))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(meddelande)
                .addGap(31, 31, 31)
                .addComponent(områdeValCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void områdeValCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_områdeValCBActionPerformed
        // TODO add your handling code here:
        jLabel2.setText(getAgentNamn());
    }//GEN-LAST:event_områdeValCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel meddelande;
    private javax.swing.JComboBox<String> områdeValCB;
    // End of variables declaration//GEN-END:variables
}
