/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mibg3.Admin;

import javax.swing.JOptionPane;
import mibg3.Valideringsklass;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author d-aly
 */
public class RegAgent extends javax.swing.JFrame {
    private InfDB mibdb;

    /**
     * Creates new form RegAgent
     */
    public RegAgent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NamnField = new javax.swing.JTextField();
        AnstDatumField = new javax.swing.JTextField();
        LösenordField = new javax.swing.JPasswordField();
        regAgLabel = new javax.swing.JLabel();
        TelField = new javax.swing.JTextField();
        AGID = new javax.swing.JLabel();
        okAlienRegKnapp = new javax.swing.JButton();
        namnLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        omrLabel = new javax.swing.JLabel();
        anstDatLabel = new javax.swing.JLabel();
        losLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        admCheckBox = new javax.swing.JCheckBox();
        omradeCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrera Agenter");

        NamnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamnFieldActionPerformed(evt);
            }
        });

        AnstDatumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnstDatumFieldActionPerformed(evt);
            }
        });

        LösenordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LösenordFieldActionPerformed(evt);
            }
        });

        regAgLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        regAgLabel.setText("Registrera Agent");

        TelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelFieldActionPerformed(evt);
            }
        });

        AGID.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AGID.setText("AgentID:");

        okAlienRegKnapp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        okAlienRegKnapp.setText("OK");
        okAlienRegKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAlienRegKnappActionPerformed(evt);
            }
        });

        namnLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        namnLabel.setText("Namn:");

        telLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        telLabel.setText("Telefon:");

        omrLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        omrLabel.setText("Område:");

        anstDatLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        anstDatLabel.setText("Anställningsdatum:");

        losLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        losLabel.setText("Lösenord:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("ID:et anges automatiskt");

        jLabel1.setText("YYYY-MM-DD");

        admCheckBox.setText("Gör till Administratör");
        admCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admCheckBoxActionPerformed(evt);
            }
        });

        omradeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Svealand", "Götaland", "Norrland", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okAlienRegKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(regAgLabel)
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AGID)
                            .addComponent(anstDatLabel)
                            .addComponent(telLabel)
                            .addComponent(namnLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NamnField)
                                    .addComponent(AnstDatumField)
                                    .addComponent(TelField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(admCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(losLabel)
                                    .addComponent(omrLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LösenordField)
                                    .addComponent(omradeCB, 0, 95, Short.MAX_VALUE))))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regAgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AGID)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namnLabel)
                    .addComponent(NamnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telLabel)
                    .addComponent(TelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anstDatLabel)
                    .addComponent(AnstDatumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(losLabel)
                    .addComponent(LösenordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(omrLabel)
                    .addComponent(omradeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okAlienRegKnapp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamnFieldActionPerformed

    private void AnstDatumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnstDatumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnstDatumFieldActionPerformed

    private void LösenordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LösenordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LösenordFieldActionPerformed

    private void TelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelFieldActionPerformed

    private void okAlienRegKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAlienRegKnappActionPerformed
        /** Lokala variabeldeklarationer. Dessa ska hämta värdet på det vi skriver in när man registrerar en ny
        * alien och ta lokalvariablerna som sedan sätts in i insert metoden för databasen så att informationen vi skriver in sätts in i databasen.
        */
        String admin;
        String namn = NamnField.getText();
        String telefon = TelField.getText();
        String lösen = LösenordField.getText();
        String omrade= omradeCB.getSelectedItem().toString();
        if(admCheckBox.isSelected()){
        admin = "J";
        }
        else{
        admin = "N";
        }
        if(Valideringsklass.giltigtLosenord(lösen) && Valideringsklass.värdeExisterar(NamnField) && Valideringsklass.värdeExisterar(TelField) && Valideringsklass.giltigtDatum(AnstDatumField)==true);{
            try{
                // Instansierar databasen.
                JOptionPane.showMessageDialog(null, admin + namn + telefon + lösen + omrade + AnstDatumField.getText());
                mibdb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
                int id = Integer.parseInt(mibdb.getAutoIncrement("Agent", "Agent_ID"));
                mibdb.insert("INSERT INTO Agent VALUES(" + id + " , " + "'" + namn + "'" + " , " + "'" + telefon + "'" + " , " + "'" + AnstDatumField.getText() + "'" + " , " + "'" + admin + "'" + " , " + "'" + lösen + "'" + " , " + omrade + ")");
                JOptionPane.showMessageDialog(null, "Grattis! En ny agent har registrerats i systemet.");

            }
            catch(InfException e){
                JOptionPane.showMessageDialog(null, "Kontrollera att fälten är korrekt formaterade.");

            }
        }

    }//GEN-LAST:event_okAlienRegKnappActionPerformed

    private void admCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admCheckBoxActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGID;
    private javax.swing.JTextField AnstDatumField;
    private javax.swing.JPasswordField LösenordField;
    private javax.swing.JTextField NamnField;
    private javax.swing.JTextField TelField;
    private javax.swing.JCheckBox admCheckBox;
    private javax.swing.JLabel anstDatLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel losLabel;
    private javax.swing.JLabel namnLabel;
    private javax.swing.JButton okAlienRegKnapp;
    private javax.swing.JLabel omrLabel;
    private javax.swing.JComboBox<String> omradeCB;
    private javax.swing.JLabel regAgLabel;
    private javax.swing.JLabel telLabel;
    // End of variables declaration//GEN-END:variables
}
